import { NextResponse } from "next/server";
import fs from "fs";
import { brandingPath } from "@/lib/branding/storage";

// Filenames are generated by generateBrandingStandard as brand-<ts>.<ext>
// / brand-<ts>-source.<ext>; validate to keep this from serving arbitrary
// paths.
const SAFE_FILENAME = /^[a-zA-Z0-9_-]+\.(html|md|png|jpg|jpeg|webp|gif)$/;

const CONTENT_TYPE_BY_EXT: Record<string, string> = {
  html: "text/html; charset=utf-8",
  md: "text/markdown; charset=utf-8",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  webp: "image/webp",
  gif: "image/gif",
};

export async function GET(
  req: Request,
  { params }: { params: Promise<{ fileName: string }> },
) {
  const { fileName } = await params;
  if (!SAFE_FILENAME.test(fileName)) {
    return NextResponse.json({ error: "Invalid file name." }, { status: 400 });
  }

  const filePath = brandingPath(fileName);
  if (!fs.existsSync(filePath)) {
    return NextResponse.json({ error: "File not found." }, { status: 404 });
  }

  const ext = fileName.split(".").pop() ?? "";
  const contentType = CONTENT_TYPE_BY_EXT[ext] ?? "application/octet-stream";
  // ?download=1 forces a save dialog; otherwise the HTML preview can render
  // inline in an <iframe> / new tab.
  const download = new URL(req.url).searchParams.get("download") === "1";
  const disposition = download ? "attachment" : "inline";

  const buffer = fs.readFileSync(filePath);
  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": contentType,
      "Content-Disposition": `${disposition}; filename="${fileName}"`,
    },
  });
}
